### ISSUE TITLE
Wrong Laravel 5 installation instructions?

### ISSUE THREAD

**Issue by ninthspace** [analogueorm/laravel-auth#1]
`"analogue/laravel-auth": "~5.0"` in composer.json pulls in a version of laravel-auth that's incompatible with Laravel 5, specifically because it references `Illuminate\Auth\UserInterface` which no longer exists.

Switching to `"analogue/laravel-auth": "dev-master"` resolves this for me.

**Comment by RemiCollin** [comment]
The instructions are correct, but the latest release wasn't tagged, which result in ~5.0 not pointing on the good commit. Should work now.

**Comment by ninthspace** [comment]
Excellent, that works now. Thank you.
