### ISSUE TITLE
Repository called in stati

### ISSUE THREAD

**Issue by mbbender** [analogueorm/laravel-auth#2]
``` php
ErrorException in AnalogueUserProvider.php line 109:
Non-static method Analogue\ORM\System\Manager::repository() should not be called statically, assuming $this from incompatible context 
```

Looks like repository is not a static function. I just installed this fresh on a basically fresh install of L5. I'm going to dig in for a bit to see if it's a simple issue.

**Comment by RemiCollin** [comment]
Yes it wasn't up to date with the latest analogue version, which uses dependency injection. Fixed in last version.
