### ISSUE TITLE
Method firstByAttributes doesn't exist

### ISSUE THREAD

**Issue by gpassarelli** [analogueorm/laravel-auth#3]
Hi there, firtst of all I would like to congrat you for the awesome package that Analogue is, I've started using and I loved it.

But after getting your laravel-auth repo I notice that I your are calling a functionon the file **AnalogueUserProvider.php** for the repository that doesn't exist anymore, maybe on a previous version on Analogue.

The function **retrieveByCredentials** calls the method _firstByAttributes_ of the repository on the return, but the repository doesn't have this function. 

So I needed to update the return to use the function _firstMatching_ of the repository. So the function **retrieveByCredentials** it will be like this:

``` php
    /**
     * Retrieve a user by the given credentials.
     *
     * @param  array $credentials
     * @return UserInterface|null
     */
    public function retrieveByCredentials(array $credentials)
    {
        $criteria = [];
        foreach ($credentials as $key => $value)
            if ( ! str_contains($key, 'password'))
                $criteria[$key] = $value;

        return $this->getRepository()->firstMatching($criteria);
    }
```

**Comment by RemiCollin** [comment]
You're right about the method call, it's using an old version of the base repository class. Fixed it in last laravel-auth release. 

Really happy you like this project. ATM I'm working on a new release with several improvements, including a documentation website, which should be online very soon.

**Comment by gpassarelli** [comment]
Hi Rémi, awesome \o/

Will it be any break changes? Because right now we are already implementing with Analogue.

**Comment by RemiCollin** [comment]
It should be 100% backward compatible.

**Comment by gpassarelli** [comment]
Nice, looking forward to hear from you.
