### ISSUE TITLE
What about returning a Guest object when the user's not logged in?

### ISSUE THREAD

**Issue by Evertt** [analogueorm/laravel-auth#6]
I started a discussion on [reddit](https://www.reddit.com/r/laravel/comments/3ncm7j/why_treat_an_unauthenticated_user_so_different/) about this and I think it might not be a bad idea.

Of course you'd need to really spell this out in the documentation, but then I think people can work with it and that it really has some advantages. The first advantage would be that you can then also apply laravel's policies to guests.

What do you think?

**Comment by RemiCollin** [comment]
We'll follow the Laravel's common behaviour, for consistency.
